# Generated by Django 2.2.5 on 2020-04-11 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=6800)),
                ('auth', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('spider_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('egg', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('if_built', models.BooleanField(default=False)),
                ('uploaded_version', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('deployed_version', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('spider_amount', models.IntegerField(default=None, null=True)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('manual', models.BooleanField(blank=True, default=True)),
                ('latest_run', models.DateTimeField(blank=True, default=None, null=True)),
                ('next_run_duration', models.IntegerField(blank=True, default=None, null=True)),
                ('available', models.BooleanField(default=True)),
                ('current_job_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_ignore_count', models.IntegerField(default=0)),
                ('page_error_count', models.IntegerField(default=0)),
                ('item_scrape_count', models.IntegerField(default=0)),
                ('item_error_count', models.IntegerField(default=0)),
                ('run_times', models.IntegerField(default=0)),
                ('run_date', models.DateField()),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Spider')),
            ],
        ),
    ]
